---
kind: pipeline
type: docker
name: linux-amd64

platform:
 arch: amd64
 os: linux

name: linux-amd64   
steps:
- name: test
  image: golang:1.14.4
  privileged: true
  failure : ignore
  environment:
    GOOS: linux
    GOARCH: amd64
   
- name: notify
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/...
    when:
    status:
    - failure
    - success
