kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    repo: sithuhtetzaw/drone
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
