kind: pipeline
name: default

steps:
- name: download  
  image: plugins/download
  settings:
    source: https://github.com/drone/drone-cli/releases/download/v0.8.5/drone_linux_amd64.tar.gz
    md5: a0524c59d5c45bf2e924465115836d37
