kind: pipeline
name: default

steps:
- name: encrypted_secret
  image: alpine
  environment:
    USERNAME:
      from_secret: username

---
kind: secret
name: username
data: 9XxxyW6R6JRRG8mFGJw7qIk4i6y1OojRLoahwACGxu84zxC/uTzBvSt7pQ==
