---
kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: python:3.7-alpine
    detach: true
    failure: ignore
    environment:
      GOOS: linux
      GOARCH: amd64
    
    when:
     status:
     - failure
     - success
