---
kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: python:3.7-alpine
    environment:
      GOOS: linux
      GOARCH: amd64
    
  - name: notify
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/...
