---
kind: pipeline
type: docker
name: default

steps:
- name: webhook
  image: tysonhtun/docker_plugin:plugin
  settings:
    url: https://tysondrone.digitalstacks.net
    method: post
    body: |
      hello world
